export const SEARCH_ROUTE = '/search/:searchTerm'
export const TABLE_ROUTE = '/Table'
export const DATA_DICTIONARY_ROUTE = '/DataDictionary'
export const DEFAULT_ROUTE = '/'
export const PRIVACY_POLICY_ROUTE = '/PrivacyPolicy'
