export const DONOR_ROUTE = '/donor/:donor'
export const DONOR_FRAGMENT_ROUTE = '/donor/'
export const TABLE_ROUTE = '/table'
export const DATA_DICTIONARY_ROUTE = '/data-dictionary'
export const DEFAULT_ROUTE = '/'
export const PRIVACY_POLICY_ROUTE = '/privacy-policy'
export const CANDIDATE_ROUTE = '/candidate'
